CREATE TABLE books(
  id INT(10) PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  author VARCHAR(200) NOT NULL,
  publisher VARCHAR(200) NOT NULL,
  year INT(4),
  isbn VARCHAR(50) UNIQUE,
  cover VARCHAR(100),
  price DECIMAL(10,2),
  status TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);